---
# tasks file for criecm.zfs
- name: OS vars
  include_tasks: '{{ includefile }}'
  with_first_found:
    - files:
        - '{{ ansible_os_family }}.yml'
  loop_control:
    loop_var: includefile
  tags: vars,zfs

- name: get zpools
  command: 'zpool list -H -o name'
  changed_when: False
  check_mode: False
  register: zpools
  tags: vars,zfs

- name: replication hosts
  include_tasks: zfs_backup.yml
  loop_control:
    loop_var: backup_host
    label: '{{ backup_host }}'
  with_items: '{{ shares | selectattr("zfsrc","defined") | selectattr("backup_on","defined") | map(attribute="backup_on") | map("regex_replace","^.*@","") | list | unique }}'
  tags: zfs,replication
  when: not restore
  register: replhosts

- name: zfs shares
  include_tasks: zfs.yml
  with_items: '{{ shares | selectattr("zfsrc","defined") | list }}'
  loop_control:
    loop_var: onezfs
  tags: zfs
  when: myzfs | length == 0 or myzfs == onezfs.name
