---
- include_vars: zfs.yml

- name: 'zfs {{ zfs.zfsrc }}'
  zfs:
    name: '{{ zfs.zfsrc }}'
    state: present
    origin: '{{ zfs.origin | default(omit) }}'
    extra_zfs_properties: '{{ zfsprops }}'
