---
- include_vars: zfs.yml

- zfs:
    name: '{{ zfs.zfsrc }}'
    state: present
    origin: '{{ zfs.origin | default(omit) }}'
    extra_zfs_properties: '{{ zfsprops }}'
  when: zfs.state | default("present") != "absent"
